### ISSUE TITLE
ReferenceError $ not defined

### ISSUE THREAD

**Issue by saraAshaikh** [Vidyo/CircularTiles#1]
ReferenceError: $ is not defined[Learn More]  VidyoConnector.html:166:2
	<anonymous> file:///D:/Vidyo/CircularTiles-master/CircularTiles-master/VidyoConnector.html:166:2

**Comment by rktalusani** [comment]
This may be a jquery related issue. https://stackoverflow.com/questions/22268881/referenceerror-is-not-defined
